### PR TITLE
Add CSS Layout News

### PR DESCRIPTION
**Pull request by ferhatelmas**

### CODE REVIEW

**Comment by vredniy** [comment]
Man, how do u find this stuff? :smile: :+1: @ferhatelmas

**Comment by ferhatelmas** [comment]
I don't really remember where I encountered first, probably some link or comment listed on HN such as http://www.kaledavis.com/2013/09/06/newsletters-newsletters-newsletters.html.

**Comment by vredniy** [comment]
@ferhatelmas Really great job. I hope together we can collect all of email newsletters :smile:

**Comment by ferhatelmas** [comment]
Hehe, I will try to help as much as I can.

**Pull request merged**
