### PR TITLE
Added Frontend Focus

### PR DESCRIPTION
**Pull request by ankane**
Added missing Cooper Press newsletters - as per #69

### CODE REVIEW

**Comment by ankane** [comment]
Done - I'll blame editing/searching in GitHub UI :)

**Comment by ferhatelmas** [comment]
@ankane no worries but sorry again for my misleading message but frontend focus is also in the list under HTML5 category.

**Comment by ferhatelmas** [comment]
@ankane it seems we covered everything from cooper press, let's close this. If I'm missing something, please, open another one not to clutter message. Thank you for your time.

**Comment by ankane** [comment]
No worries, thanks for the awesome project 👍

**Pull request closed without merging**
